version: '3'
dotenv: [.env]

vars:
  PACKAGE_IMPORT_NAME: mlops_course
  PYTHON_VERSION: 3.11

tasks:
  create-venv:
    desc: Create a virtual environment
    cmds:
      - uv venv -p {{.PYTHON_VERSION}} .venv
    silent: false

  dev-install:
    desc: Sync project dependencies with optionals
    cmds:
      - rm -rf .venv
      - task: create-venv
      - uv sync --extra dev

  sync-test:
    desc: Sync only test dependencies
    cmds:
        - rm -rf .venv
        - task: create-venv
        - uv sync --extra test
        # - source .venv/Scripts/activate && uv sync --extra test # Activate and sync

  test:
    desc: Run unit test and coverage
    cmds:
      - task: sync-test
      - pytest --cov src/mlops_course --cov-report=html:_artifact/coverage_re --cov-report=term-missing --cov-config=.coveragerc
      - 'echo "Note: you can open the HTML report with: open _artifact/coverage_re/index.html"'

  qa-lines-count:
    desc: Count the number of lines in each *.py script (excluding .venv)
    cmds:
      - echo "--> Count the number of lines in each *.py script (excluding .venv)"
      - >
        find . -path ./.venv -prune -o -name '*.py' -exec wc -l {} \; |
        sort -n |
        awk '{printf "%4s %s\n", $1, $2}{s+=$1}END{print s}'

  pc:
    desc: Run pre-commit hooks
    cmds:
      - task: sync-dev
      - uv run pre-commit run --all-files

  lint:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files

  help:
    desc: Print all tasks defined in the Taskfile
    cmd: task -l
    silent: true

  default:
    cmds:
      - task: help
    silent: true
